# Language
language: node_js
node_js:
- 11

dist: xenial

services:
  - xvfb

addons:
  chrome: stable

# Branches to build
branches:
  only:
  - master

before_install:
- export TZ=America/Los_Angeles
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

# Build
script:
- npm install
- npm run packagr
- ng test --watch=false

# Notifications
notifications:
  email:
    recipients:
    - chengkuang@gmail.com
    on_success: change
    on_failure: change
