# Language
language: node_js
node_js:
- 11

dist: xenial

services:
  - xvfb

addons:
  chrome: stable

# Branches to build
branches:
  only:
  - master

before_install:
- export TZ=America/Los_Angeles
- export CHROME_BIN=chromium-browser

# Build
script:
- npm install
- npm run packagr
- ng test --watch=false

# Notifications
notifications:
  email:
    recipients:
    - chengkuang@gmail.com
    on_success: change
    on_failure: change
