import {Injectable} from '@angular/core';

/**
 * interface for the timezone with abbreviation and offset
 */
export interface TimeZoneAbbrMapping {
  timezone: string;
  offset: number;
  abbreviation: string;
}

@Injectable()
export class DemoService {
  /**
   * get timezones with timezone abbreviation and offset.
   */
  getTimezoneAbbrMappings(): TimeZoneAbbrMapping[] {
    /**
     * Below timezones are adapted from:
     * https://github.com/kevalbhatt/timezone-picker/blob/master/src/timezones.json,
     * https://www.timeanddate.com/time/zones,
     * https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations
     *
     * The MIT License (MIT)
     * Copyright (c) 2015 Keval Bhatt
     * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
     * associated documentation files (the "Software"), to deal in the Software without restriction,
     * including without limitation the rights to use, copy, modify, merge, publish, distribute,
     * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
     * furnished to do so, subject to the following conditions:
     * The above copyright notice and this permission notice shall be included in all copies or
     * substantial portions of the Software.
     */
    return [
        { timezone: 'Australia/Adelaide',  offset: 10.5,  abbreviation: 'ACDT' },
        // { timezone: 'Australia/Broken_Hill',  offset: 10.5,  abbreviation: 'ACDT' },
        { timezone: 'Australia/Darwin',  offset: 9.5,  abbreviation: 'ACST' },
        { timezone: 'America/Eirunepe',  offset: -5,  abbreviation: 'ACT' },
        // { timezone: 'America/Rio_Branco',  offset: -5,  abbreviation: 'ACT' },
        { timezone: 'Australia/Eucla',  offset: 8.75,  abbreviation: 'ACWST' },
        { timezone: 'America/Halifax',  offset: -3,  abbreviation: 'ADT' },
        // { timezone: 'Australia/Currie',  offset: 11,  abbreviation: 'AEDT' },
        // { timezone: 'Australia/Hobart',  offset: 11,  abbreviation: 'AEDT' },
        // { timezone: 'Australia/Melbourne',  offset: 11,  abbreviation: 'AEDT' },
        { timezone: 'Australia/Sydney',  offset: 11,  abbreviation: 'AEDT' },
        { timezone: 'Australia/Brisbane',  offset: 10,  abbreviation: 'AEST' },
        // { timezone: 'Australia/Lindeman',  offset: 10,  abbreviation: 'AEST' },
        { timezone: 'Asia/Kabul',  offset: 4.5,  abbreviation: 'AFT' },
        { timezone: 'America/Anchorage',  offset: -8,  abbreviation: 'AKDT' },
        { timezone: 'America/Anchorage',  offset: -9,  abbreviation: 'AKST' },
        // { timezone: 'America/Juneau',  offset: -9,  abbreviation: 'AKST' },
        // { timezone: 'America/Nome',  offset: -9,  abbreviation: 'AKST' },
        // { timezone: 'America/Sitka',  offset: -9,  abbreviation: 'AKST' },
        // { timezone: 'America/Yakutat',  offset: -9,  abbreviation: 'AKST' },
        { timezone: 'Asia/Almaty',  offset: 6,  abbreviation: 'ALMT' },
        { timezone: 'America/Campo_Grande',  offset: -3,  abbreviation: 'AMST' },
        // { timezone: 'America/Cuiaba',  offset: -3,  abbreviation: 'AMST' },
        // { timezone: 'America/Boa_Vista',  offset: -4,  abbreviation: 'AMT' },
        { timezone: 'America/Manaus',  offset: -4,  abbreviation: 'AMT' },
        // { timezone: 'America/Porto_Velho',  offset: -4,  abbreviation: 'AMT' },
        { timezone: 'Asia/Yerevan',  offset: 4,  abbreviation: 'AMT' },
        { timezone: 'Asia/Anadyr',  offset: 12,  abbreviation: 'ANAT' },
        { timezone: 'Asia/Aqtau',  offset: 5,  abbreviation: 'AQTT' },
        // { timezone: 'Asia/Aqtobe',  offset: 5,  abbreviation: 'AQTT' },
        // { timezone: 'America/Argentina/Salta',  offset: -3,  abbreviation: 'ART' },
        { timezone: 'America/Argentina/Buenos_Aires',  offset: -3,  abbreviation: 'ART' },
        // { timezone: 'America/Argentina/Catamarca',  offset: -3,  abbreviation: 'ART' },
        // { timezone: 'America/Argentina/Cordoba',  offset: -3,  abbreviation: 'ART' },
        // { timezone: 'America/Argentina/Jujuy',  offset: -3,  abbreviation: 'ART' },
        // { timezone: 'America/Argentina/La_Rioja',  offset: -3,  abbreviation: 'ART' },
        // { timezone: 'America/Argentina/Mendoza',  offset: -3,  abbreviation: 'ART' },
        // { timezone: 'America/Argentina/Rio_Gallegos',  offset: -3,  abbreviation: 'ART' },
        // { timezone: 'America/Argentina/San_Juan',  offset: -3,  abbreviation: 'ART' },
        // { timezone: 'America/Argentina/San_Luis',  offset: -3,  abbreviation: 'ART' },
        // { timezone: 'America/Argentina/Tucuman',  offset: -3,  abbreviation: 'ART' },
        // { timezone: 'America/Argentina/Ushuaia',  offset: -3,  abbreviation: 'ART' },
        // { timezone: 'America/Anguilla',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Antigua',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Aruba',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Barbados',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Blanc-Sablon',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Curacao',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Dominica',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Glace_Bay',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Goose_Bay',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Grand_Turk',  offset: -5,  abbreviation: 'AST' },
        // { timezone: 'America/Grenada',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Guadeloupe',  offset: -4,  abbreviation: 'AST' },
        { timezone: 'America/Halifax',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Kralendijk',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Lower_Princes',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Marigot',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Martinique',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Moncton',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Montserrat',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Port_of_Spain',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Puerto_Rico',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Santo_Domingo',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/St_Barthelemy',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Thule',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/St_Kitts',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/St_Lucia',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/St_Thomas',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/St_Vincent',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'America/Tortola',  offset: -4,  abbreviation: 'AST' },
        // { timezone: 'Atlantic/Bermuda',  offset: -4,  abbreviation: 'AST' },
        { timezone: 'Asia/Aden',  offset: 3,  abbreviation: 'AST' },
        // { timezone: 'Asia/Baghdad',  offset: 3,  abbreviation: 'AST' },
        // { timezone: 'Asia/Bahrain',  offset: 3,  abbreviation: 'AST' },
        // { timezone: 'Asia/Kuwait',  offset: 3,  abbreviation: 'AST' },
        // { timezone: 'Asia/Qatar',  offset: 3,  abbreviation: 'AST' },
        // { timezone: 'Asia/Riyadh',  offset: 3,  abbreviation: 'AST' },
        // { timezone: 'Atlantic/Bermuda',  offset: -4,  abbreviation: 'AST' },
        { timezone: 'Australia/Perth',  offset: 8,  abbreviation: 'AWST' },
        { timezone: 'Atlantic/Azores',  offset: 0,  abbreviation: 'AZOST' },
        { timezone: 'Atlantic/Azores',  offset: -1,  abbreviation: 'AZOT' },
        { timezone: 'Asia/Baku',  offset: 4,  abbreviation: 'AZT' },
        { timezone: 'Asia/Brunei',  offset: 8,  abbreviation: 'BNT' },
        { timezone: 'America/La_Paz',  offset: -4,  abbreviation: 'BOT' },
        { timezone: 'America/Sao_Paulo',  offset: -2,  abbreviation: 'BRST' },
        { timezone: 'America/Araguaina',  offset: -3,  abbreviation: 'BRT' },
        // { timezone: 'America/Bahia',  offset: -2,  abbreviation: 'BRT' },
        // { timezone: 'America/Belem',  offset: -3,  abbreviation: 'BRT' },
        // { timezone: 'America/Fortaleza',  offset: -3,  abbreviation: 'BRT' },
        // { timezone: 'America/Maceio',  offset: -3,  abbreviation: 'BRT' },
        // { timezone: 'America/Recife',  offset: -3,  abbreviation: 'BRT' },
        // { timezone: 'America/Santarem',  offset: -3,  abbreviation: 'BRT' },
        { timezone: 'Asia/Dhaka',  offset: 6,  abbreviation: 'BST' },
        { timezone: 'Europe/London',  offset: 1,  abbreviation: 'BST' },
        { timezone: 'Asia/Thimphu',  offset: 6,  abbreviation: 'BTT' },
        { timezone: 'Africa/Blantyre',  offset: 2,  abbreviation: 'CAT' },
        // { timezone: 'Africa/Bujumbura',  offset: 2,  abbreviation: 'CAT' },
        // { timezone: 'Africa/Gaborone',  offset: 2,  abbreviation: 'CAT' },
        // { timezone: 'Africa/Harare',  offset: 2,  abbreviation: 'CAT' },
        // { timezone: 'Africa/Kigali',  offset: 2,  abbreviation: 'CAT' },
        // { timezone: 'Africa/Lubumbashi',  offset: 2,  abbreviation: 'CAT' },
        // { timezone: 'Africa/Lusaka',  offset: 2,  abbreviation: 'CAT' },
        // { timezone: 'Africa/Maputo',  offset: 2,  abbreviation: 'CAT' },
        { timezone: 'Indian/Cocos',  offset: 6.5,  abbreviation: 'CCT' },
        { timezone: 'America/Chicago',  offset: -5,  abbreviation: 'CDT' },
        { timezone: 'Europe/Brussels',  offset: 2,  abbreviation: 'CEST' },
        // { timezone: 'Africa/Algiers',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Africa/Ceuta',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Africa/Tunis',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Arctic/Longyearbyen',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Amsterdam',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Andorra',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Belgrade',  offset: 1,  abbreviation: 'CET' },
        { timezone: 'Europe/Berlin',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Budapest',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Bratislava',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Brussels',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Copenhagen',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Gibraltar',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Ljubljana',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Luxembourg',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Madrid',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Malta',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Monaco',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Oslo',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Paris',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Podgorica',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Prague',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Rome',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/San_Marino',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Sarajevo',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Skopje',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Stockholm',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Tirane',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Vaduz',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Vatican',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Vienna',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Warsaw',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Zagreb',  offset: 1,  abbreviation: 'CET' },
        // { timezone: 'Europe/Zurich',  offset: 1,  abbreviation: 'CET' },
        { timezone: 'Pacific/Chatham',  offset: 13.75,  abbreviation: 'CHADT' },
        { timezone: 'Pacific/Chatham',  offset: 12.75,  abbreviation: 'CHAST' },
        { timezone: 'Asia/Choibalsan',  offset: 9,  abbreviation: 'CHOST' },
        { timezone: 'Asia/Choibalsan',  offset: 8,  abbreviation: 'CHOT' },
        { timezone: 'Pacific/Guam',  offset: 10,  abbreviation: 'ChST' },
        // { timezone: 'Pacific/Saipan',  offset: 10,  abbreviation: 'ChST' },
        { timezone: 'Pacific/Chuuk',  offset: 10,  abbreviation: 'CHUT' },
        { timezone: 'Pacific/Rarotonga',  offset: -10,  abbreviation: 'CKT' },
        { timezone: 'America/Santiago',  offset: -3,  abbreviation: 'CLST' },
        { timezone: 'America/Santiago',  offset: -4,  abbreviation: 'CLT' },
        { timezone: 'America/Bogota',  offset: -5,  abbreviation: 'COT' },
        // { timezone: 'America/Bahia_Banderas',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Belize',  offset: -6,  abbreviation: 'CST' },
        { timezone: 'America/Chicago',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Costa_Rica',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/El_Salvador',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Guatemala',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Havana',  offset: -5,  abbreviation: 'CST' },
        // { timezone: 'America/Indiana/Tell_City',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Indiana/Knox',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Managua',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Matamoros',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Menominee',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Mexico_City',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Merida',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Monterrey',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/North_Dakota/Beulah',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/North_Dakota/Center',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/North_Dakota/New_Salem',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Rainy_River',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Rankin_Inlet',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Regina',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Resolute',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Swift_Current',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Tegucigalpa',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'America/Winnipeg',  offset: -6,  abbreviation: 'CST' },
        // { timezone: 'Asia/Chongqing',  offset: 8,  abbreviation: 'CST' },
        // { timezone: 'Asia/Harbin',  offset: 8,  abbreviation: 'CST' },
        // { timezone: 'Asia/Macau',  offset: 8,  abbreviation: 'CST' },
        { timezone: 'Asia/Shanghai',  offset: 8,  abbreviation: 'CST' },
        // { timezone: 'Asia/Taipei',  offset: 8,  abbreviation: 'CST' },
        { timezone: 'Atlantic/Cape_Verde',  offset: -1,  abbreviation: 'CVT' },
        { timezone: 'Indian/Christmas',  offset: 7,  abbreviation: 'CXT' },
        { timezone: 'Antarctica/Davis',  offset: 7,  abbreviation: 'DAVT' },
        { timezone: 'Pacific/Easter',  offset: -5,  abbreviation: 'EASST' },
        { timezone: 'Pacific/Easter',  offset: -6,  abbreviation: 'EAST' },
        { timezone: 'Africa/Addis_Ababa',  offset: 3,  abbreviation: 'EAT' },
        // { timezone: 'Africa/Asmara',  offset: 3,  abbreviation: 'EAT' },
        // { timezone: 'Africa/Dar_es_Salaam',  offset: 3,  abbreviation: 'EAT' },
        // { timezone: 'Africa/Djibouti',  offset: 3,  abbreviation: 'EAT' },
        // { timezone: 'Africa/Juba',  offset: 3,  abbreviation: 'EAT' },
        // { timezone: 'Africa/Kampala',  offset: 3,  abbreviation: 'EAT' },
        // { timezone: 'Africa/Khartoum',  offset: 3,  abbreviation: 'EAT' },
        // { timezone: 'Africa/Mogadishu',  offset: 3,  abbreviation: 'EAT' },
        // { timezone: 'Africa/Nairobi',  offset: 3,  abbreviation: 'EAT' },
        // { timezone: 'Indian/Antananarivo',  offset: 3,  abbreviation: 'EAT' },
        // { timezone: 'Indian/Comoro',  offset: 3,  abbreviation: 'EAT' },
        // { timezone: 'Indian/Mayotte',  offset: 3,  abbreviation: 'EAT' },
        { timezone: 'America/Guayaquil',  offset: -5,  abbreviation: 'ECT' },
        { timezone: 'America/New_York',  offset: -4,  abbreviation: 'EDT' },
        { timezone: 'Europe/Bucharest',  offset: 3,  abbreviation: 'EEST' },
        // { timezone: 'Africa/Cairo',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Africa/Tripoli',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Asia/Amman',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Asia/Beirut',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Asia/Damascus',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Asia/Gaza',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Asia/Hebron',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Asia/Nicosia',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Europe/Athens',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Europe/Bucharest',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Europe/Chisinau',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Europe/Helsinki',  offset: 2,  abbreviation: 'EET' },
        { timezone: 'Europe/Istanbul',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Europe/Kaliningrad',  offset: 3,  abbreviation: 'EET' },
        // { timezone: 'Europe/Kiev',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Europe/Mariehamn',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Europe/Riga',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Europe/Sofia',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Europe/Tallinn',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Europe/Uzhgorod',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Europe/Vilnius',  offset: 2,  abbreviation: 'EET' },
        // { timezone: 'Europe/Zaporozhye',  offset: 2,  abbreviation: 'EET' },
        { timezone: 'America/Scoresbysund',  offset: -1,  abbreviation: 'EGT' },
        // { timezone: 'America/Atikokan',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Cancun',  offset: -6,  abbreviation: 'EST' },
        // { timezone: 'America/Cayman',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Coral_Harbour',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Detroit',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Indiana/Petersburg',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Indiana/Vevay',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Indiana/Indianapolis',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Indiana/Marengo',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Indiana/Vincennes',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Indiana/Winamac',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Iqaluit',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Jamaica',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Kentucky/Louisville',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Kentucky/Monticello',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Montreal',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Nassau',  offset: -5,  abbreviation: 'EST' },
        { timezone: 'America/New_York',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Nipigon',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Panama',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Pangnirtung',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Port-au-Prince',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Thunder_Bay',  offset: -5,  abbreviation: 'EST' },
        // { timezone: 'America/Toronto',  offset: -5,  abbreviation: 'EST' },
        { timezone: 'Pacific/Fiji',  offset: 13,  abbreviation: 'FJST' },
        { timezone: 'Pacific/Fiji',  offset: 12,  abbreviation: 'FJT' },
        { timezone: 'Atlantic/Stanley',  offset: -3,  abbreviation: 'FKST' },
        { timezone: 'Atlantic/Stanley',  offset: -4,  abbreviation: 'FKT' },
        { timezone: 'America/Noronha',  offset: -2,  abbreviation: 'FNT' },
        { timezone: 'Pacific/Galapagos',  offset: -6,  abbreviation: 'GALT' },
        { timezone: 'Pacific/Gambier',  offset: -9,  abbreviation: 'GAMT' },
        { timezone: 'Asia/Tbilisi',  offset: 4,  abbreviation: 'GET' },
        { timezone: 'America/Cayenne',  offset: -3,  abbreviation: 'GFT' },
        { timezone: 'Pacific/Tarawa',  offset: 12,  abbreviation: 'GILT' },
        // { timezone: 'Africa/Abidjan',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Africa/Accra',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Africa/Bamako',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Africa/Banjul',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Africa/Bissau',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Africa/Conakry',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Africa/Dakar',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Africa/Freetown',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Africa/Lome',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Africa/Monrovia',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Africa/Nouakchott',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Africa/Ouagadougou',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Africa/Sao_Tome',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'America/Danmarkshavn',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Atlantic/Reykjavik',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Atlantic/St_Helena',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Europe/Dublin',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Europe/Guernsey',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Europe/Isle_of_Man',  offset: 0,  abbreviation: 'GMT' },
        // { timezone: 'Europe/Jersey',  offset: 0,  abbreviation: 'GMT' },
        { timezone: 'Europe/London',  offset: 0,  abbreviation: 'GMT' },
        { timezone: 'Asia/Dubai',  offset: 4,  abbreviation: 'GST' },
        // { timezone: 'Asia/Muscat',  offset: 4,  abbreviation: 'GST' },
        { timezone: 'Atlantic/South_Georgia',  offset: -2,  abbreviation: 'GST' },
        { timezone: 'America/Guyana',  offset: -4,  abbreviation: 'GYT' },
        { timezone: 'America/Adak',  offset: -9,  abbreviation: 'HDT' },
        { timezone: 'Asia/Hong_Kong',  offset: 8,  abbreviation: 'HKT' },
        { timezone: 'Asia/Hovd',  offset: 8,  abbreviation: 'HOVST' },
        { timezone: 'Asia/Hovd',  offset: 7,  abbreviation: 'HOVT' },
        { timezone: 'America/Adak',  offset: -10,  abbreviation: 'HST' },
        // { timezone: 'Pacific/Honolulu',  offset: -10,  abbreviation: 'HST' },
        // { timezone: 'Pacific/Johnston',  offset: -10,  abbreviation: 'HST' },
        { timezone: 'Asia/Bangkok',  offset: 7,  abbreviation: 'ICT' },
        // { timezone: 'Asia/Ho_Chi_Minh',  offset: 7,  abbreviation: 'ICT' },
        // { timezone: 'Asia/Phnom_Penh',  offset: 7,  abbreviation: 'ICT' },
        // { timezone: 'Asia/Vientiane',  offset: 7,  abbreviation: 'ICT' },
        { timezone: 'Asia/Jerusalem',  offset: 3,  abbreviation: 'IDT' },
        { timezone: 'Indian/Chagos',  offset: 6,  abbreviation: 'IOT' },
        { timezone: 'Asia/Tehran',  offset: 4.5,  abbreviation: 'IRDT' },
        { timezone: 'Asia/Irkutsk',  offset: 9,  abbreviation: 'IRKT' },
        { timezone: 'Asia/Tehran',  offset: 3.5,  abbreviation: 'IRST' },
        { timezone: 'Asia/Colombo',  offset: 5.5,  abbreviation: 'IST' },
        // { timezone: 'Asia/Jerusalem',  offset: 2,  abbreviation: 'IST' },
        // { timezone: 'Asia/Calcutta',  offset: 5.5,  abbreviation: 'IST' },
        { timezone: 'Asia/Tokyo',  offset: 9,  abbreviation: 'JST' },
        { timezone: 'Asia/Bishkek',  offset: 6,  abbreviation: 'KGT' },
        { timezone: 'Pacific/Kosrae',  offset: 11,  abbreviation: 'KOST' },
        { timezone: 'Asia/Krasnoyarsk',  offset: 8,  abbreviation: 'KRAST' },
        { timezone: 'Asia/Krasnoyarsk',  offset: 7,  abbreviation: 'KRAT' },
        // { timezone: 'Asia/Novokuznetsk',  offset: 7,  abbreviation: 'KRAT' },
        // { timezone: 'Asia/Pyongyang',  offset: 9,  abbreviation: 'KST' },
        { timezone: 'Asia/Seoul',  offset: 9,  abbreviation: 'KST' },
        { timezone: 'Australia/Lord_Howe',  offset: 11,  abbreviation: 'LHDT' },
        { timezone: 'Pacific/Kiritimati',  offset: 14,  abbreviation: 'LINT' },
        { timezone: 'Asia/Magadan',  offset: 12,  abbreviation: 'MAGT' },
        { timezone: 'Pacific/Marquesas',  offset: -9.5,  abbreviation: 'MART' },
        { timezone: 'Antarctica/Mawson',  offset: 5,  abbreviation: 'MAWT' },
        // { timezone: 'Pacific/Kwajalein',  offset: 12,  abbreviation: 'MHT' },
        { timezone: 'Pacific/Majuro',  offset: 12,  abbreviation: 'MHT' },
        { timezone: 'Antarctica/Macquarie',  offset: 11,  abbreviation: 'MIST' },
        { timezone: 'Asia/Rangoon',  offset: 6.5,  abbreviation: 'MMT' },
        { timezone: 'Europe/Moscow',  offset: 4,  abbreviation: 'MSD' },
        // { timezone: 'Europe/Minsk',  offset: 3,  abbreviation: 'MSK' },
        { timezone: 'Europe/Moscow',  offset: 3,  abbreviation: 'MSK' },
        // { timezone: 'America/Boise',  offset: -7,  abbreviation: 'MST' },
        // { timezone: 'America/Cambridge_Bay',  offset: -7,  abbreviation: 'MST' },
        // { timezone: 'America/Chihuahua',  offset: -7,  abbreviation: 'MST' },
        // { timezone: 'America/Creston',  offset: -7,  abbreviation: 'MST' },
        // { timezone: 'America/Dawson_Creek',  offset: -7,  abbreviation: 'MST' },
        // { timezone: 'America/Denver',  offset: -7,  abbreviation: 'MST' },
        { timezone: 'America/Edmonton',  offset: -7,  abbreviation: 'MST' },
        // { timezone: 'America/Hermosillo',  offset: -7,  abbreviation: 'MST' },
        // { timezone: 'America/Inuvik',  offset: -7,  abbreviation: 'MST' },
        // { timezone: 'America/Mazatlan',  offset: -7,  abbreviation: 'MST' },
        // { timezone: 'America/Ojinaga',  offset: -7,  abbreviation: 'MST' },
        // { timezone: 'America/Phoenix',  offset: -7,  abbreviation: 'MST' },
        // { timezone: 'America/Yellowknife',  offset: -7,  abbreviation: 'MST' },
        { timezone: 'Indian/Mauritius',  offset: 4,  abbreviation: 'MUT' },
        { timezone: 'Indian/Maldives',  offset: 5,  abbreviation: 'MVT' },
        // { timezone: 'Asia/Kuala_Lumpur',  offset: 8,  abbreviation: 'MYT' },
        { timezone: 'Asia/Kuching',  offset: 8,  abbreviation: 'MYT' },
        { timezone: 'Pacific/Noumea',  offset: 11,  abbreviation: 'NCT' },
        { timezone: 'Pacific/Norfolk',  offset: 11,  abbreviation: 'NFT' },
        { timezone: 'Asia/Novosibirsk',  offset: 7,  abbreviation: 'NOVT' },
        { timezone: 'Asia/Kathmandu',  offset: 5.75,  abbreviation: 'NPT' },
        { timezone: 'Pacific/Nauru',  offset: 12,  abbreviation: 'NRT' },
        { timezone: 'America/St_Johns',  offset: -3.5,  abbreviation: 'NST' },
        { timezone: 'Pacific/Niue',  offset: -11,  abbreviation: 'NUT' },
        { timezone: 'Pacific/Auckland',  offset: 13,  abbreviation: 'NZDT' },
        { timezone: 'Pacific/Auckland',  offset: 12,  abbreviation: 'NZST' },
        { timezone: 'Asia/Omsk',  offset: 7,  abbreviation: 'OMSST' },
        { timezone: 'Asia/Omsk',  offset: 6,  abbreviation: 'OMST' },
        { timezone: 'Asia/Oral',  offset: 5,  abbreviation: 'ORAT' },
        // { timezone: 'America/Los_Angeles',  offset: -7,  abbreviation: 'PDT' },
        { timezone: 'America/Vancouver',  offset: -7,  abbreviation: 'PDT' },
        { timezone: 'America/Lima',  offset: -5,  abbreviation: 'PET' },
        { timezone: 'Asia/Kamchatka',  offset: 12,  abbreviation: 'PETST' },
        { timezone: 'Asia/Kamchatka',  offset: 12,  abbreviation: 'PETT' },
        { timezone: 'Pacific/Port_Moresby',  offset: 10,  abbreviation: 'PGT' },
        { timezone: 'Pacific/Enderbury',  offset: 13,  abbreviation: 'PHOT' },
        { timezone: 'Asia/Manila',  offset: 8,  abbreviation: 'PHT' },
        { timezone: 'Asia/Karachi',  offset: 5,  abbreviation: 'PKT' },
        { timezone: 'America/Miquelon',  offset: -2,  abbreviation: 'PMDT' },
        { timezone: 'America/Miquelon',  offset: -3,  abbreviation: 'PMST' },
        { timezone: 'Pacific/Pohnpei',  offset: 11,  abbreviation: 'PONT' },
        // { timezone: 'America/Dawson',  offset: -8,  abbreviation: 'PST' },
        // { timezone: 'America/Los_Angeles',  offset: -8,  abbreviation: 'PST' },
        // { timezone: 'America/Metlakatla',  offset: -8,  abbreviation: 'PST' },
        // { timezone: 'America/Santa_Isabel',  offset: -8,  abbreviation: 'PST' },
        // { timezone: 'America/Tijuana',  offset: -8,  abbreviation: 'PST' },
        { timezone: 'America/Vancouver',  offset: -8,  abbreviation: 'PST' },
        // { timezone: 'America/Whitehorse',  offset: -8,  abbreviation: 'PST' },
        // { timezone: 'Asia/Manila',  offset: 8,  abbreviation: 'PST' },
        // { timezone: 'Pacific/Pitcairn',  offset: -8,  abbreviation: 'PST' },
        { timezone: 'Pacific/Palau',  offset: 9,  abbreviation: 'PWT' },
        { timezone: 'America/Asuncion',  offset: -3,  abbreviation: 'PYST' },
        { timezone: 'America/Asuncion',  offset: -4,  abbreviation: 'PYT' },
        { timezone: 'Asia/Qyzylorda',  offset: 6,  abbreviation: 'QYZT' },
        { timezone: 'Indian/Reunion',  offset: 4,  abbreviation: 'RET' },
        { timezone: 'Asia/Sakhalin',  offset: 11,  abbreviation: 'SAKT' },
        { timezone: 'Europe/Samara',  offset: 4,  abbreviation: 'SAMT' },
        // { timezone: 'Africa/Johannesburg',  offset: 2,  abbreviation: 'SAST' },
        { timezone: 'Africa/Mbabane',  offset: 2,  abbreviation: 'SAST' },
        // { timezone: 'Africa/Maseru',  offset: 2,  abbreviation: 'SAST' },
        { timezone: 'Pacific/Guadalcanal',  offset: 11,  abbreviation: 'SBT' },
        { timezone: 'Indian/Mahe',  offset: 4,  abbreviation: 'SCT' },
        { timezone: 'Asia/Singapore',  offset: 8,  abbreviation: 'SGT' },
        { timezone: 'Asia/Srednekolymsk',  offset: 11,  abbreviation: 'SRET' },
        { timezone: 'America/Paramaribo',  offset: -3,  abbreviation: 'SRT' },
        { timezone: 'Pacific/Midway',  offset: -11,  abbreviation: 'SST' },
        // { timezone: 'Pacific/Pago_Pago',  offset: -11,  abbreviation: 'SST' },
        { timezone: 'Pacific/Tahiti',  offset: -10,  abbreviation: 'TAHT' },
        { timezone: 'Indian/Kerguelen',  offset: 5,  abbreviation: 'TFT' },
        { timezone: 'Asia/Dushanbe',  offset: 5,  abbreviation: 'TJT' },
        { timezone: 'Pacific/Fakaofo',  offset: 13,  abbreviation: 'TKT' },
        { timezone: 'Asia/Dili',  offset: 9,  abbreviation: 'TLT' },
        { timezone: 'Asia/Ashgabat',  offset: 5,  abbreviation: 'TMT' },
        { timezone: 'Pacific/Tongatapu',  offset: 13,  abbreviation: 'TOT' },
        { timezone: 'Pacific/Funafuti',  offset: 12,  abbreviation: 'TVT' },
        { timezone: 'Asia/Ulaanbaatar',  offset: 9,  abbreviation: 'ULAST' },
        { timezone: 'Asia/Ulaanbaatar',  offset: 8,  abbreviation: 'ULAT' },
        { timezone: 'Etc/UTC',  offset: 0,  abbreviation: 'UTC' },
        { timezone: 'America/Montevideo',  offset: -2,  abbreviation: 'UYST' },
        { timezone: 'America/Montevideo',  offset: -3,  abbreviation: 'UYT' },
        { timezone: 'Asia/Samarkand',  offset: 5,  abbreviation: 'UZT' },
        // { timezone: 'Asia/Tashkent',  offset: 5,  abbreviation: 'UZT' },
        { timezone: 'America/Caracas',  offset: -4,  abbreviation: 'VET' },
        { timezone: 'Asia/Vladivostok',  offset: 11,  abbreviation: 'VLAST' },
        { timezone: 'Asia/Vladivostok',  offset: 10,  abbreviation: 'VLAT' },
        { timezone: 'Antarctica/Vostok',  offset: 6,  abbreviation: 'VOST' },
        { timezone: 'Pacific/Efate',  offset: 11,  abbreviation: 'VUT' },
        { timezone: 'Pacific/Wake',  offset: 12,  abbreviation: 'WAKT' },
        { timezone: 'Africa/Windhoek',  offset: 2,  abbreviation: 'WAST' },
        { timezone: 'Africa/Bangui',  offset: 1,  abbreviation: 'WAT' },
        // { timezone: 'Africa/Brazzaville',  offset: 1,  abbreviation: 'WAT' },
        // { timezone: 'Africa/Douala',  offset: 1,  abbreviation: 'WAT' },
        // { timezone: 'Africa/Kinshasa',  offset: 1,  abbreviation: 'WAT' },
        // { timezone: 'Africa/Lagos',  offset: 1,  abbreviation: 'WAT' },
        // { timezone: 'Africa/Libreville',  offset: 1,  abbreviation: 'WAT' },
        // { timezone: 'Africa/Luanda',  offset: 1,  abbreviation: 'WAT' },
        // { timezone: 'Africa/Malabo',  offset: 1,  abbreviation: 'WAT' },
        // { timezone: 'Africa/Ndjamena',  offset: 1,  abbreviation: 'WAT' },
        // { timezone: 'Africa/Niamey',  offset: 1,  abbreviation: 'WAT' },
        // { timezone: 'Africa/Porto-Novo',  offset: 1,  abbreviation: 'WAT' },
        { timezone: 'Europe/Lisbon',  offset: 1,  abbreviation: 'WEST' },
        // { timezone: 'Africa/Casablanca',  offset: 0,  abbreviation: 'WET' },
        // { timezone: 'Africa/El_Aaiun',  offset: 0,  abbreviation: 'WET' },
        // { timezone: 'Atlantic/Canary',  offset: 0,  abbreviation: 'WET' },
        // { timezone: 'Atlantic/Faroe',  offset: 0,  abbreviation: 'WET' },
        // { timezone: 'Atlantic/Madeira',  offset: 0,  abbreviation: 'WET' },
        { timezone: 'Europe/Lisbon',  offset: 0,  abbreviation: 'WET' },
        { timezone: 'Pacific/Wallis',  offset: 12,  abbreviation: 'WFT'},
        { timezone: 'America/Godthab',  offset: -3,  abbreviation: 'WGT' },
        // { timezone: 'Asia/Jakarta',  offset: 7,  abbreviation: 'WIB' },
        { timezone: 'Asia/Pontianak',  offset: 7,  abbreviation: 'WIB' },
        { timezone: 'Asia/Jayapura',  offset: 9,  abbreviation: 'WIT' },
        { timezone: 'Asia/Makassar',  offset: 8,  abbreviation: 'WITA' },
        { timezone: 'Pacific/Apia',  offset: 14,  abbreviation: 'WSDT' },
        // { timezone: 'Asia/Kashgar',  offset: 6,  abbreviation: 'XJT' },
        { timezone: 'Asia/Urumqi',  offset: 6,  abbreviation: 'XJT' },
        { timezone: 'Asia/Yakutsk',  offset: 10,  abbreviation: 'YAKT' },
        { timezone: 'Asia/Yekaterinburg',  offset: 6,  abbreviation: 'YEKST' },
        { timezone: 'Asia/Yekaterinburg',  offset: 5,  abbreviation: 'YEKT' }
    ];
  }
}
